"""
discord_osint/pipeline/stages/reporting_stage.py
-------------------------------------------------
ReportingStage – generate the AI persona summary, optional AI
markdown report, and the HTML output file.

Change log
----------
- Honours the pipeline cancellation token. The AI persona summary and
  AI structured report both make long Groq calls (~30–45 s each); if the
  user hit Stop, both are skipped. The HTML report still runs — it's
  local and fast — so the analyst keeps whatever was collected.
- Report file paths are recorded in ``intel_core.intel["report_paths"]``
  so the persisted JSON snapshot is self-describing. Previously the paths
  were only carried by SSE events, so a job inspected later (via
  ``/api/investigations/<id>``) had no way to link the snapshot back to
  its report file without globbing.
- Failure modes are logged via ``log_trace`` in addition to the console
  print, so a run with DEBUG on retains a durable record.

Phase 3 edit retained
---------------------
The HTML report is generated by
``discord_osint.intelligence.html_report.generate_html_report()``,
which produces a fully self-contained dark-themed document with
collapsible platform cards, structured breach info, and the Phase 1
intelligence + Phase 2 pivot sections natively embedded.
"""

from __future__ import annotations

import datetime
import os

from ..base import Stage, EmitFn
from ..context import InvestigationContext
from ...utils import CACHE_DIR, log_trace
from ...reporting import (
    generate_persona_summary,
    generate_ai_report,
    format_ai_report_markdown,
)
from ...errors import ReportGenerationError


class ReportingStage(Stage):
    name = "reporting"

    def run(self, ctx: InvestigationContext, emit: EmitFn = lambda *_: None) -> None:
        cfg        = ctx.config
        intel_core = ctx.intel_core
        target_id  = ctx.target_id
        ts         = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

        cancel_event = getattr(cfg, "_cancel_event", None)

        def _is_cancelled() -> bool:
            return cancel_event is not None and cancel_event.is_set()

        report_paths: dict[str, str] = {}

        # ------------------------------------------------------------------ #
        # 1. AI persona summary                                               #
        # ------------------------------------------------------------------ #
        if cfg.ENABLE_AI_REPORT and cfg.GROQ_API_KEY:
            if _is_cancelled():
                print("  Persona summary skipped (pipeline cancelled).")
                log_trace("ReportingStage: persona summary skipped — cancelled.")
            else:
                print("\n-- Generating Persona Summary --")
                emit("progress", {"message": "Generating AI persona summary"})
                try:
                    persona = generate_persona_summary(intel_core.intel, cfg.GROQ_API_KEY)
                    if persona:
                        intel_core.add_intel("persona_summary", "persona", persona,
                                             source="ai_persona")
                        emit("finding", {"type": "persona_summary"})
                except Exception as exc:
                    print(f"  Persona summary error: {exc}")
                    log_trace(f"ReportingStage: persona summary failed: "
                              f"{type(exc).__name__}: {exc}")

        # ------------------------------------------------------------------ #
        # 2. AI structured report (markdown)                                  #
        # ------------------------------------------------------------------ #
        if cfg.ENABLE_AI_REPORT and cfg.GROQ_API_KEY:
            if _is_cancelled():
                print("  AI report skipped (pipeline cancelled).")
                log_trace("ReportingStage: AI markdown report skipped — cancelled.")
            else:
                print("\n-- Generating AI report --")
                emit("progress", {"message": "Generating AI structured report"})
                try:
                    structured = generate_ai_report(intel_core, cfg.GROQ_API_KEY)
                    if structured:
                        md = format_ai_report_markdown(structured)
                        rp = os.path.join(CACHE_DIR, f"report_{target_id}_{ts}.md")
                        with open(rp, "w", encoding="utf-8") as f:
                            f.write(md)
                        print(f"  AI report saved to {rp}")
                        emit("report_ready", {"path": rp, "format": "markdown"})
                        report_paths["markdown"] = rp
                except Exception as exc:
                    print(f"  AI report error: {exc}")
                    log_trace(f"ReportingStage: AI markdown report failed: "
                              f"{type(exc).__name__}: {exc}")

        # ------------------------------------------------------------------ #
        # 3. HTML report (dark-themed generator)                              #
        # ------------------------------------------------------------------ #
        # Runs regardless of cancellation: it's a local template render with
        # no network calls, so producing it even on a cancelled run gives
        # the analyst something usable rather than nothing.
        output_format = getattr(cfg, "OUTPUT_FORMAT", "html")
        if output_format == "html":
            print("\n-- Generating HTML report --")
            emit("progress", {"message": "Generating HTML report"})
            try:
                from ...intelligence.html_report import generate_html_report as _gen_html

                html_path    = os.path.join(CACHE_DIR, f"report_{target_id}_{ts}.html")
                html_content = _gen_html(intel_core, target_id)

                with open(html_path, "w", encoding="utf-8") as f:
                    f.write(html_content)
                print(f"  HTML report saved to {html_path}")
                emit("report_ready", {"path": html_path, "format": "html"})
                report_paths["html"] = html_path
            except Exception as exc:
                log_trace(f"ReportingStage: HTML report failed: "
                          f"{type(exc).__name__}: {exc}")
                raise ReportGenerationError(str(exc)) from exc

        # ------------------------------------------------------------------ #
        # 4. Record report paths in the intel snapshot                        #
        # ------------------------------------------------------------------ #
        if report_paths:
            intel_core.intel["report_paths"] = report_paths

        # Clean up temporary keys
        intel_core.intel.pop("scraped_urls", None)
        print("\n== Reporting stage complete ==")