"""
discord_osint/pipeline/stages/reporting_stage.py
-------------------------------------------------
ReportingStage – generate the AI persona summary, optional AI
markdown report, and the HTML output file.

Phase 3 edit
------------
The HTML report is now generated by
``discord_osint.intelligence.html_report.generate_html_report()``,
which produces a fully self-contained dark-themed document with
collapsible platform cards, structured breach info, and the Phase 1
intelligence + Phase 2 pivot sections natively embedded.

The legacy AI persona summary and markdown report are unchanged.
"""

from __future__ import annotations

import datetime
import os

from ..base import Stage, EmitFn
from ..context import InvestigationContext
from ...utils import CACHE_DIR
from ...reporting import (
    generate_persona_summary,
    generate_ai_report,
    format_ai_report_markdown,
)
from ...errors import ReportGenerationError


class ReportingStage(Stage):
    name = "reporting"

    def run(self, ctx: InvestigationContext, emit: EmitFn = lambda *_: None) -> None:
        cfg        = ctx.config
        intel_core = ctx.intel_core
        target_id  = ctx.target_id
        ts         = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

        # ------------------------------------------------------------------ #
        # 1. AI persona summary                                               #
        # ------------------------------------------------------------------ #
        if cfg.ENABLE_AI_REPORT and cfg.GROQ_API_KEY:
            print("\n-- Generating Persona Summary --")
            emit("progress", {"message": "Generating AI persona summary"})
            try:
                persona = generate_persona_summary(intel_core.intel, cfg.GROQ_API_KEY)
                if persona:
                    intel_core.add_intel("persona_summary", "persona", persona, source="ai_persona")
                    emit("finding", {"type": "persona_summary"})
            except Exception as exc:
                print(f"  Persona summary error: {exc}")

        # ------------------------------------------------------------------ #
        # 2. AI structured report (markdown)                                  #
        # ------------------------------------------------------------------ #
        if cfg.ENABLE_AI_REPORT and cfg.GROQ_API_KEY:
            print("\n-- Generating AI report --")
            emit("progress", {"message": "Generating AI structured report"})
            try:
                structured = generate_ai_report(intel_core, cfg.GROQ_API_KEY)
                if structured:
                    md = format_ai_report_markdown(structured)
                    rp = os.path.join(CACHE_DIR, f"report_{target_id}_{ts}.md")
                    with open(rp, "w", encoding="utf-8") as f:
                        f.write(md)
                    print(f"  AI report saved to {rp}")
                    emit("report_ready", {"path": rp, "format": "markdown"})
            except Exception as exc:
                print(f"  AI report error: {exc}")

        # ------------------------------------------------------------------ #
        # 3. HTML report (new dark-themed generator)                          #
        # ------------------------------------------------------------------ #
        output_format = getattr(cfg, "OUTPUT_FORMAT", "html")
        if output_format == "html":
            print("\n-- Generating HTML report --")
            emit("progress", {"message": "Generating HTML report"})
            try:
                from ...intelligence.html_report import generate_html_report as _gen_html

                html_path    = os.path.join(CACHE_DIR, f"report_{target_id}_{ts}.html")
                html_content = _gen_html(intel_core, target_id)

                with open(html_path, "w", encoding="utf-8") as f:
                    f.write(html_content)
                print(f"  HTML report saved to {html_path}")
                emit("report_ready", {"path": html_path, "format": "html"})
            except Exception as exc:
                raise ReportGenerationError(str(exc)) from exc

        # Clean up temporary keys
        intel_core.intel.pop("scraped_urls", None)
        print("\n== Reporting stage complete ==")
